package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strings"
)

// ParsedField is a field read from an existing Go struct via AST.
type ParsedField struct {
	GoName    string
	DBName    string
	GoType    string
	RefTable  string // from ref:"table" struct tag
	ExtraTags string // non-gen tags preserved across regen (e.g. validate:"required")
}

// readStructFields parses filename and returns the fields of structName.
// Returns nil if the file does not exist or the struct is not found.
func readStructFields(filename, structName string) ([]ParsedField, error) {
	src, err := os.ReadFile(filename)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, src, 0)
	if err != nil {
		// Return empty rather than hard-fail on unparseable user code.
		return nil, nil
	}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != structName {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			return collectParsedFields(st), nil
		}
	}
	return nil, nil
}

func collectParsedFields(st *ast.StructType) []ParsedField {
	var out []ParsedField
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue // embedded
		}
		pf := ParsedField{
			GoName: f.Names[0].Name,
			GoType: exprStr(f.Type),
		}
		if f.Tag != nil {
			pf.DBName = structTagValue(f.Tag.Value, "db")
			pf.RefTable = structTagValue(f.Tag.Value, "ref")
			pf.ExtraTags = extractExtraTags(f.Tag.Value)
		}
		if pf.DBName == "" {
			pf.DBName = toSnakeCase(pf.GoName)
		}
		out = append(out, pf)
	}
	return out
}

func exprStr(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.Ident:
		return v.Name
	case *ast.StarExpr:
		return "*" + exprStr(v.X)
	case *ast.SelectorExpr:
		return exprStr(v.X) + "." + v.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprStr(v.Elt)
	}
	return "any"
}

func structTagValue(tagLit, key string) string {
	tag := strings.Trim(tagLit, "`")
	return reflect.StructTag(tag).Get(key)
}

// extractExtraTags returns all struct tag key:"value" pairs except those
// generated by gen (db, json, ref), so they survive a genDomainSection rewrite.
func extractExtraTags(tagLit string) string {
	tag := strings.Trim(tagLit, "`")
	var extra []string
	
	for tag != "" {
		// Skip leading space
		tag = strings.TrimLeft(tag, " ")
		if tag == "" {
			break
		}
		
		// Find key
		colon := strings.Index(tag, ":")
		if colon < 0 {
			break // invalid tag
		}
		key := tag[:colon]
		
		// Value must start with quote
		tag = tag[colon+1:]
		if len(tag) == 0 || tag[0] != '"' {
			break
		}
		
		// Find end of value
		endQuote := 1
		for endQuote < len(tag) {
			if tag[endQuote] == '"' && tag[endQuote-1] != '\\' {
				break
			}
			endQuote++
		}
		if endQuote >= len(tag) {
			break // unclosed quote
		}
		
		val := tag[:endQuote+1]
		
		// Include if not managed by gen
		switch key {
		case "db", "json", "ref":
			// skip
		default:
			extra = append(extra, key+":"+val)
		}
		
		tag = tag[endQuote+1:]
	}
	
	return strings.Join(extra, " ")
}
